/** A user's own film/talent grades for one prospect. Row of user_prospect_grades. */
export interface UserProspectGrade {
  user_id: string
  prospect_id: number
  film_grade: number | null
  talent_grade: number | null
  /** Generated by Postgres — see computeMyGrade() in lib/user-grade.ts. */
  my_grade: number | null
  created_at: string
  updated_at: string
}

/**
 * PUT body for /api/scouting-grades. Omitting a field leaves it unchanged;
 * sending null clears it. Clearing both should DELETE instead.
 */
export interface SaveProspectGradeRequest {
  prospect_id: number
  film_grade?: number | null
  talent_grade?: number | null
}
